[toolchain]
package_manager = "yarn"
anchor_version = "0.29.0"

[features]
resolution = true
skip-lint = false
idl-build = ["anchor-lang/idl-build"]

[programs.localnet]
counter_ts = "74QZ1uTUKCPsao19wAtRRxxQ441PeejhkAZBH7nw9EEN"

[programs.devnet]
vault = "HDhkebca19sS5qcas1DXkCQJoxN6upiEvc8wYZvFp4y7"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/Office/solana-smartcontracts/counter-ts/myprogram-keypair.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[workspace]
members = [
  "programs/counter-ts",
  "programs/vault"
]
